[package]
name = "factoryfactory"
version = "0.2.1"
edition = "2024"

[dependencies]
bevy = "0.16.0"
bevy-inspector-egui = "0.31.0"
bevy_embedded_assets = "0.13.0-rc.1"
bincode = "2.0.1"
flate2 = "1.1.1"
noise = "0.9.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
