[package]
name = "factoryfactory"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bincode = "2.0.1"
flate2 = "1.1.1"
noise = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
